# Generated by Django 4.0.4 on 2022-05-05 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_customer_store_custo_last_na_2e448d_idx'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Addres',
            new_name='Address',
        ),
        migrations.RenameModel(
            old_name='FavoriteItems',
            new_name='FavoriteItem',
        ),
    ]
